import pygame
from support import import_folder
import numpy as np
import time

class Player(pygame.sprite.Sprite):
    def __init__(self,pos,update_score, update_frames):
        #AI Considerations
        self.update_score = update_score
        self.update_frames = update_frames

        #player setup
        super().__init__()
        self.import_character_assets()
        self.frame_index = 0
        self.animation_speed = 0.15
        self.image = self.animations['idle'][self.frame_index]
        self.rect = self.image.get_rect(topleft = pos)
        
        #player movement
        self.direction = pygame.math.Vector2(0,0)
        self.speed = 5
        self.gravity = 0.8
        self.jump_speed = -15

        #player state
        self.state = 'idle'
        self.facing_right = True
        self.on_ground = False
        self.on_ceiling = False
        self.on_left = False
        self.on_right = False

    def import_character_assets(self):
        character_path = 'AIControlledPlatformer/assets/character/'
        self.animations = {'idle':[], 'run':[], 'jump':[], 'fall':[]}
        
        for animation in self.animations.keys():
            full_path = character_path + animation
            self.animations[animation] = import_folder(full_path)

    def animate(self):
        animation = self.animations[self.state]

        #loop over frames of animation
        self.frame_index += self.animation_speed
        if self.frame_index >= len(animation):
            self.frame_index = 0
        
        #deal with flipping character direction
        image = animation[int(self.frame_index)]
        if self.facing_right:
            self.image = image
        else:
            flipped_image = pygame.transform.flip(image, True, False)
            self.image = flipped_image

        #set collision
        if self.on_ground and self.on_right:
            self.rect = self.image.get_rect(bottomright = self.rect.bottomright)
        elif self.on_ground and self.on_left:
            self.rect = self.image.get_rect(bottomleft = self.rect.bottomleft)
        elif self.on_ground:
            self.rect = self.image.get_rect(midbottom = self.rect.midbottom)
        elif self.on_ceiling and self.on_right:
            self.rect = self.image.get_rect(topright = self.rect.topright)
        elif self.on_ceiling and self.on_left:
            self.rect = self.image.get_rect(topleft = self.rect.topleft)
        elif self.on_ceiling:
            self.rect = self.image.get_rect(midtop = self.rect.midtop)

    #Modified input method for AI, will accept action generated by AI
    def get_input(self, action):
        self.update_frames
        #AI movement considerations
        #[right, left, up-right, up-left]
        #apply gravity to ai so it doesn't stack jumps and fly away...
        #chickens can't fly.
        if not self.on_ground:
            self.apply_gravity()
            if np.array_equal(action, [1, 0, 0, 0]):
                self.direction.x = 1
            elif np.array_equal(action, [0, 1, 0, 0]):
                self.direction.x = -1
            elif np.array_equal(action, [0, 0, 1, 0]):
                self.direction.x = 1
            elif np.array_equal(action, [0, 0, 0, 1]):
                self.direction.x = -1
            else:
                self.direction.x = 0
        else:
            if np.array_equal(action, [1, 0, 0, 0]):
                self.direction.x = 1
            elif np.array_equal(action, [0, 1, 0, 0]):
                self.direction.x = -1
            elif np.array_equal(action, [0, 0, 1, 0]):
                self.direction.x = 1
                self.jump()
            elif np.array_equal(action, [0, 0, 0, 1]):
                self.direction.x = -1
                self.jump()
            else:
                self.direction.x = 0

        #key input for player movement
        # keys = pygame.key.get_pressed()

        # if keys[pygame.K_d]:
        #     self.direction.x = 1
        #     self.facing_right = True
        # elif keys[pygame.K_a]:
        #     self.direction.x = -1
        #     self.facing_right = False
        # else:
        #     self.direction.x = 0

        # if keys[pygame.K_SPACE] and self.on_ground:
        #     self.jump()

    def get_state(self):
        if self.direction.y < 0:
            self.state = 'jump'
        elif self.direction.y > 1:
            self.state = 'fall'
        else:
            if self.direction.x != 0:
                self.state = 'run'
            else:
                self.state = 'idle'

    def apply_gravity(self):
         self.direction.y += self.gravity
         self.rect.y += self.direction.y

    def jump(self):
        self.direction.y = self.jump_speed

    def update(self, action):
        self.get_input(action)
        self.get_state()
        self.animate()
        
        